### ISSUE TITLE
Bug: Fails to start in a VMWare Fusion VM

### ISSUE THREAD

**Issue by dnaka91** [khonsulabs/gooey#93] opened 2023-12-19 08:42 UTC
Was trying out gooey in VM on my Mac (Arch Linux guest with Cinnamon DE), and it fails to start up. Can see the window flicker for a second, but it immediately crashes.

Not sure if you can do anything about it, though. The logs say that `xrandr` reports the display with 0mm size, it fails to iterate over rendering targets and in the end it fails somewhere deep in `wgpu_hal`.

This all happens in the `winit` and `wgpu` crates, so it's maybe more of a problem on their side rather than something in gooey itself. Likely just a matter of time for those crates to support who the hardware is exposed in VMWare products.

Still wanted to put it out here to keep track of it.

**Comment by dnaka91** [comment] 2023-12-19 16:30
I get a few warnings and one error, but all logs from winit/wgpu. But in the end, I get the same "Unsupported uniform datatype!" panic in my case.

For me, the error happens on both X11 and Wayland, but I'll check for any differences in the logs tomrrow.

**Comment by ecton** [comment] 2023-12-19 17:07
No rush, it sounds like you're experiencing the same issue. Thank you!

**Comment by ecton** [comment] 2023-12-19 20:01
I can't seem to force this bug on my machine directly. I need to get a virtual machine going. I have however pushed code to Kludgine in a PR that *might* fix the issue, if my Googling led me in the right direction. If anyone who can reproduce this would look at khonsulabs/kludgine#68's branch and try running any example, it would test my attempt at a blind fix.

```sh
git clone https://github.com/khonsulabs/kludgine .
cd kludgine
git switch unsupported-uniform
cargo run --example basic
```

Kludgine's examples do not enable any logging, so I don't expect to learn anything new. Either this will work and the bug is fixed, or it will crash like Gooey.

**Comment by ecton** [comment] 2023-12-19 22:18
Thank you for testing it! I'll get a new update out today or tomorrow with this in it.

**Comment by ecton** [comment] 2023-12-19 23:13
This should be fixed by ensuring Cargo has pulled kludgine v0.6.1.

**Comment by ecton** [comment] 2023-12-20 01:44
v0.1.3 has been released that includes the updated version Kludgine. Let me know if Gooey now works successfully or if there's a new panic :) I still will get a VM set up one of these days.

**Comment by dnaka91** [comment] 2023-12-20 10:47
It starts now, but is only a blank (black) window. When dragging it around one of the widgets starts to be drawn partially but the rest stays black.

That probable has to do with vulkan having issues to initialize:

```
2023-12-20T10:44:59.343542Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane    
2023-12-20T10:44:59.343789Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-12-20T10:44:59.368772Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2023-12-20T10:44:59.376082Z  INFO wgpu_hal::vulkan::instance: Instance version: 0x403111    
2023-12-20T10:44:59.376105Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw    
2023-12-20T10:44:59.376110Z  INFO wgpu_hal::vulkan::instance: Enabling device properties2    
2023-12-20T10:44:59.377391Z  INFO wgpu_hal::gles::egl: Loading Wayland library to get the current display    
2023-12-20T10:44:59.377463Z  INFO wgpu_hal::gles::egl: Loading X11 library to get the current display    
2023-12-20T10:44:59.378545Z  INFO wgpu_hal::gles::egl: Using X11 platform    
2023-12-20T10:44:59.378574Z  INFO wgpu_hal::gles::egl: Enabling EGL debug output    
2023-12-20T10:44:59.777273Z  INFO wgpu_hal::gles::egl: Display vendor "Mesa Project", version (1, 4)    
2023-12-20T10:44:59.777303Z  INFO wgpu_hal::gles::egl: 	EGL surface: +srgb khr    
2023-12-20T10:44:59.777309Z  INFO wgpu_hal::gles::egl: 	Trying native-render    
2023-12-20T10:44:59.777340Z  INFO wgpu_hal::gles::egl: 	EGL context: +debug KHR    
2023-12-20T10:44:59.777346Z  WARN wgpu_hal::gles::egl: 	EGL context: -robust access    
2023-12-20T10:44:59.780409Z  INFO wgpu_hal::gles::egl: 	EGL context: +surfaceless    
2023-12-20T10:44:59.781120Z ERROR wgpu_hal::vulkan::instance: enumerate_adapters: Initialization of an object has failed    
2023-12-20T10:44:59.782408Z  INFO wgpu_hal::gles::egl: Max label length: 256    
2023-12-20T10:44:59.782425Z  INFO wgpu_hal::gles::egl: Enabling GLES debug output    
2023-12-20T10:44:59.783023Z  INFO wgpu_core::instance: Adapter Gl AdapterInfo { name: "SVGA3D; build: RELEASE;  LLVM;", vendor: 0, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }    
2023-12-20T10:44:59.794830Z  INFO wgpu_hal::gles::device: 	Compiled shader NativeShader(5)    
2023-12-20T10:44:59.795666Z  INFO wgpu_hal::gles::device: 	Compiled shader NativeShader(6)    
2023-12-20T10:44:59.798893Z  INFO wgpu_hal::gles::device: 	Linked program NativeProgram(4)    
2023-12-20T10:44:59.825776Z  INFO cosmic_text::font::system: Parsed 953 font faces in 26ms.    
2023-12-20T10:44:59.889459Z  INFO wgpu_core::device::global: configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Rgba8UnormSrgb, width: 800, height: 600, present_mode: Fifo, alpha_mode: Auto, view_formats: [] }    
2023-12-20T10:44:59.889526Z  INFO wgpu_core::device::global: Automatically choosing alpha mode by rule Auto. Chose Opaque    
```

**Comment by ecton** [comment] 2023-12-20 17:21
Thank you both for trying it out, sorry it's not working yet! I've spent the last few hours trying to get wgpu to force itself into GL mode on my machine to make it easier to debug, and I just cannot get wgpu to use OpenGL. None of my searching through wgpu's issues found anything interesting relating to the behavior you're seeing.

In a way, I'm glad it's happening both in Wayland and x11. That hopefully means it's something I can fix! Kludgine isn't doing anything that interesting, so I'm curious what it will end up being. I'm going to table this for today, though, as my brain can only take so much of trying to get things running with very little feedback each day!

**Comment by ecton** [comment] 2023-12-27 03:41
Apparently the virtual machine I set up works (Mint with Cinnamon, I should have looked at what @dnaka91 was actually using rather than just googling cinnamon linux and downloading one of the first distros :laughing:).

I'm pretty sure this confirms the key is OpenGL, as this vm launches with vulkan + llvmpipe and works great. I'll take another stab at another distro tomorrow. I'm not sure an Arch VM looks very easy to set up... @your-sudden-death if you don't mind sharing, what distro is your VM running?

**Comment by dnaka91** [comment] 2023-12-27 03:45
Mine is Arch with Cinnamon. Specifically using EndeavorOS, which is just Arch with a graphical installer and a few presets here and there.

But using that VM for quite a while now so I'll set up a fresh one in the coming days to make sure it's not just some weird setup or missing package on my side.

Also, using the latest VMware Fusion on a x86_64 Mac, as that might affect how the hardware is exposed/emulated.

**Comment by ecton** [comment] 2023-12-27 03:46
I'm nearly 100% confident after tonight that I just need to get a distro that doesn't have Vulkan by default. I'll give EndeavorOS a go!

**Comment by ecton** [comment] 2023-12-27 04:23
I can reproduce it, and my main suspicion is correct: the OpenGL backend for wgpu doesn't honor scissor rect updates, which Kludgine uses to clip the drawing calls to the widget bounds. I'll create a simple example to report it but also attempt to work around it.

**Comment by ecton** [comment] 2023-12-27 06:29
I haven't tested my workaround extensively -- clipping may be broken in other ways by the workaround I put in. However, that's better than *all* user interfaces being broken. If you pull Gooey and make sure `Cargo.lock` has no changes, you should have the workaround I attempted in Kludgine.

I've so far had trouble creating a minimal example to report to the wgpu project. According to the documentation, my workaround should have no effect since all drawing calls are happening before the final set_scissor_rect call.

**Comment by ecton** [comment] 2023-12-27 15:07
I'm going to close this issue as resolved. Please let me know if you're still having issues!

I've opened an issue in the Kludgine project where the workaround was applied to track down and report it to wgpu.

**Closed by ecton** 2023-12-27 15:07 UTC
